Repository microsoft/wpa, pull requests merged in 2021-03, with the labels that each got.

#106 Bugfix: update `one2one_freq()`
  R/one2one_freq.R
Labels: bug

#99 Refactor: implement information value calculations natively
  DESCRIPTION
  NAMESPACE
  R/IV_by_Period.R
  R/IV_report.R
  R/calculate_IV.R
  R/create_IV.R
  man-roxygen/iv.R
  man/IV_by_period.Rd
  man/IV_report.Rd
  man/calculate_IV.Rd
  man/create_IV.Rd
  man/map_IV.Rd
Labels: refactor

#34 Documentation: add Data Validation Guide to Analyst Guide
  .github/analyst_guide.md
  .github/analyst_guide_data_validation.md
  .github/analyst_guide_getting_started.md
  _pkgdown.yml
Labels: documentation

#108 Enhancement: update mgrcoatt_dist.R
  R/mgrcoatt_dist.R
Labels: enhancement

#107 Documentation: update installation instructions
  .github/analyst_guide_getting_started.md
  .github/faq.md
Labels: documentation

#112 Feature: add create_rank_combine()
  NAMESPACE
  NEWS.md
  R/collaboration_rank.R
  R/create_rank.R
  R/email_rank.R
  R/meeting_rank.R
  R/one2one_rank.R
  R/workloads_rank.R
  _pkgdown.yml
  man/collaboration_rank.Rd
  man/create_rank.Rd
  man/create_rank_combine.Rd
  man/email_rank.Rd
  man/meeting_rank.Rd
  man/one2one_rank.Rd
  man/workloads_rank.Rd
Labels: enhancement

#105 Feature: introduce enhancements to network functions
  NEWS.md
  R/network_g2g.R
  R/network_p2p.R
  man/network_g2g.Rd
  man/network_leiden.Rd
  man/network_louvain.Rd
  man/network_p2p.Rd
Labels: enhancement
