Repository microsoft/wpa, pull requests merged in 2021-02, with the labels that each got.

#55 Feature: working patterns and flexibility index
  DESCRIPTION
  NAMESPACE
  R/flex_index.R
  R/plot_flex_index.R
  R/workpatterns_area.R
  R/workpatterns_classify.R
  R/workpatterns_classify_bw.R
  R/workpatterns_classify_pav.R
  R/workpatterns_hclust.R
  R/workpatterns_report.R
  man/flex_index.Rd
  man/personas_hclust.Rd
  man/plot_flex_index.Rd
  man/workpatterns_area.Rd
  man/workpatterns_classify.Rd
  man/workpatterns_classify_bw.Rd
  man/workpatterns_classify_pav.Rd
  man/workpatterns_hclust.Rd
  man/workpatterns_report.Rd
Labels: enhancement

#62 Bug Fix: `flag_outlooktime()` throwing up error on Standard Person Queries
  R/flag_outlooktime.R
  man/flag_outlooktime.Rd
Labels: bug

#63 Documentation: add wpa R library Playbook
  .github/playbook_intro.md
  R/flex_index.R
  _pkgdown.yml
  man/flex_index.Rd
Labels: documentation

#64 Feature: General Feature Enhancements for v1.4.0.
  NAMESPACE
  R/create_rank.R
  R/globals.R
  R/meeting_extract.R
  R/meeting_quality.R
  R/mt_data.R
  R/network_g2g.R
  data/mt_data.rda
  man/meeting_extract.Rd
  man/meeting_quality.Rd
  man/mt_data.Rd
  man/network_g2g.Rd
Labels: enhancement

#76 Bug Fix: reading double-byte characters in `import_wpa()`
  R/import_wpa.R
  man/import_wpa.Rd
Labels: bug

#79 Bug fix: no return for `collab_line()`
  R/collaboration_line.R
Labels: bug

#81 Bugfix: relax variable name checks to `collab_area()`
  R/collaboration_area.R
  man/collaboration_area.Rd
Labels: bug

#84 Feature: improvements to `network_g2g()`
  R/network_g2g.R
  man/network_g2g.Rd
Labels: enhancement

#85 Feature: return typed data for `mgrrel_matrix()`
  R/mgrrel_matrix.R
  man/mgrrel_matrix.Rd
Labels: enhancement

#75 Bug Fix: issues with Information Value functions
  NAMESPACE
  R/IV_report.R
  R/create_IV.R
  man/create_IV.Rd
  man/plot_WOE.Rd
Labels: bug

#86 Feature: create `import_to_fst()`
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/import_to_fst.R
  man/import_to_fst.Rd
Labels: enhancement

#66 Feature: create `identify_shifts_wp()`
  NAMESPACE
  R/identify_shifts_wp.R
  man/flex_index.Rd
  man/identify_shifts_wp.Rd
  man/personas_hclust.Rd
  man/plot_flex_index.Rd
  man/workpatterns_area.Rd
  man/workpatterns_classify.Rd
  man/workpatterns_classify_bw.Rd
  man/workpatterns_classify_pav.Rd
  man/workpatterns_hclust.Rd
Labels: enhancement

#69 Feature: update plot visuals in `collaboration_report()`
  R/check_query.R
  R/collaboration_report.R
  R/create_rank.R
Labels: enhancement

#87 Feature: further refinements to `collaboration_report()`
  R/check_query.R
  R/collaboration_report.R
  R/extract_hr.R
  man/collaboration_report.Rd
  man/extract_hr.Rd
Labels: enhancement
