Repository microsoft/wpa, pull requests merged in 2021-07, with the labels that each got.

#163 Article: profiling with rank functions
  vignettes/profiles-with-rank.Rmd
Labels: documentation

#162 Feature: add function for anonymizing data
  NAMESPACE
  NEWS.md
  R/anonymise.R
  man/anonymise.Rd
  man/jitter_metrics.Rd
Labels: enhancement

#160 Feature: improvements to working patterns and flexibility index
  NEWS.md
  R/create_bar_asis.R
  R/flex_index.R
  R/identify_shifts_wp.R
  R/workpatterns_classify.R
  R/workpatterns_classify_bw.R
  man/flex_index.Rd
  man/identify_shifts_wp.Rd
  man/workpatterns_classify.Rd
  man/workpatterns_classify_bw.Rd
Labels: enhancement

#166 Release: CRAN Submission Changes for v1.6.0
  .Rbuildignore
  .github/faq.md
  CRAN-RELEASE
  DESCRIPTION
  NEWS.md
  R/anonymise.R
  R/create_rank.R
  R/track_hr_change.R
  README.md
  cran-comments.md
  man/anonymise.Rd
  man/create_rank.Rd
  man/create_rank_combine.Rd
  man/jitter_metrics.Rd
  man/track_HR_change.Rd
Labels: documentation

#167 Documentation: fix documentation issues
  .github/faq.md
  R/network_g2g.R
  man/network_g2g.Rd
Labels: documentation

#169 Feature: implement Doc Search
  _pkgdown.yml
Labels: documentation, enhancement
