Repository microsoft/wpa, pull requests merged in 2021-04, with the labels that each got.

#118 Aesthetics: improve the look and feel of `create_trend()`
  DESCRIPTION
  NEWS.md
  R/create_trend.R
  R/init.R
Labels: aesthetics

#122 Docs: documentation changes for CRAN release
  CRAN-RELEASE
  DESCRIPTION
  NEWS.md
  R/check_query.R
  R/dv_data.R
  R/em_data.R
  R/g2g_data.R
  R/generate_report.R
  R/init.R
  R/mt_data.R
  R/p2p_data_sim.R
  R/sq_data.R
  R/supporting_functions.R
  R/workpatterns_classify_bw.R
  R/workpatterns_classify_pav.R
  R/workpatterns_hclust.R
  cran-comments.md
  man/add_cat.Rd
  man/camel_clean.Rd
  man/check_inputs.Rd
  man/check_person_query.Rd
  man/check_pkg_installed.Rd
  man/check_query_validation.Rd
  man/combine_signals.Rd
  man/cut_hour.Rd
  man/dv_data.Rd
  man/em_data.Rd
  man/extract_date_range.Rd
  man/extract_hr.Rd
  man/g2g_data.Rd
  man/generate_chunks.Rd
  man/heat_colours.Rd
  man/is_date_format.Rd
  man/maxmin.Rd
  man/md2html.Rd
  man/mt_data.Rd
  man/p_test.Rd
  man/pairwise_count.Rd
  man/plot_WOE.Rd
  man/plot_signal_clust.Rd
  man/read_preamble.Rd
  man/rgb2hex.Rd
  man/run_hour_splits.Rd
  man/run_sum_hr.Rd
  man/sq_data.Rd
  man/totals_bind.Rd
  man/totals_col.Rd
  man/totals_reorder.Rd
  man/tstamp.Rd
  man/us_to_space.Rd
  man/workpatterns_classify_bw.Rd
  man/workpatterns_classify_pav.Rd
  man/wrap.Rd
Labels: documentation

#119 Aesthetics: visual improvements to plots
  .github/analyst_guide_getting_started.md
  .github/faq.md
  DESCRIPTION
  NEWS.md
  R/create_bar.R
  R/create_bar_asis.R
  R/create_boxplot.R
  R/create_dist.R
  R/create_fizz.R
  R/create_hist.R
  R/create_line.R
  R/create_period_scatter.R
  R/create_scatter.R
  R/create_stacked.R
  R/create_trend.R
  R/workpatterns_classify_bw.R
  R/workpatterns_rank.R
  R/workpatterns_report.R
  README.md
  man/plot_workpatterns_classify_bw.Rd
Labels: aesthetics

#127 Feature: change the default plot return for `workpatterns_classify()`
  R/workpatterns_classify.R
  R/workpatterns_classify_bw.R
  R/workpatterns_report.R
  man/plot_workpatterns_classify_bw.Rd
  man/workpatterns_classify.Rd
  man/workpatterns_classify_bw.Rd
Labels: enhancement

#110 Fix: update functions to align with PBI logic
  R/identify_nkw.R
  R/mgrrel_matrix.R
  man/identify_nkw.Rd
Labels: bug, enhancement

#130 Feature: improve return outputs of working patterns functions
  R/init.R
  R/workpatterns_classify.R
  R/workpatterns_classify_bw.R
  man/workpatterns_classify.Rd
Labels: enhancement, refactor

#128 Documentation: credit authors for individual functions
  R/IV_by_Period.R
  R/create_bar.R
  R/create_rank.R
  R/export.R
  R/generate_report.R
  R/mgrrel_matrix.R
  R/network_describe.R
  R/p_test.R
  R/period_change.R
  R/personas_hclust.R
  R/remove_outliers.R
  R/tm_cooc.R
  R/track_hr_change.R
  R/workpatterns_classify.R
  R/workpatterns_classify_bw.R
  R/workpatterns_classify_pav.R
  man/IV_by_period.Rd
  man/create_rank.Rd
  man/export.Rd
  man/generate_report.Rd
  man/mgrrel_matrix.Rd
  man/p_test.Rd
  man/period_change.Rd
  man/personas_hclust.Rd
  man/remove_outliers.Rd
  man/tm_cooc.Rd
  man/track_HR_change.Rd
  man/workpatterns_classify.Rd
  man/workpatterns_classify_bw.Rd
  man/workpatterns_classify_pav.Rd
Labels: documentation
