Repository microsoft/wpa, pull requests merged in 2021-01, with the labels that each got.

#32 Feature: add Community Detection capability for network plots
  DESCRIPTION
  NAMESPACE
  R/create_sankey.R
  R/network_describe.R
  R/network_leiden.R
  R/network_louvain.R
  R/pairwise_count.R
  man/create_sankey.Rd
  man/network_describe.Rd
  man/network_leiden.Rd
  man/network_louvain.Rd
  man/pairwise_count.Rd
Labels: enhancement

#41 Feature: improvements and refactors to p2p functions
  NAMESPACE
  R/network_describe.R
  R/network_louvain.R
  R/network_p2p.R
  R/p2p_data_sim.R
  man/add_cat.Rd
  man/network_p2p.Rd
  man/p2p_data_sim.Rd
Labels: enhancement, refactor

#39 Feature: IV with p value
  NAMESPACE
  R/create_IV.R
  R/p_test.R
  man/create_IV.Rd
  man/p_test.Rd
  period_change.R
Labels: enhancement

#47 Documentation: unwrap examples
  .github/pull_request_template.md
  NAMESPACE
  R/afterhours_dist.R
  R/create_IV.R
  R/create_line.R
  R/flag_ch_ratio.R
  R/flag_outlooktime.R
  R/globals.R
  R/hr_trend.R
  R/identify_churn.R
  R/identify_query.R
  R/identify_tenure.R
  R/is_date_format.R
  R/network_leiden.R
  R/network_louvain.R
  R/network_p2p.R
  R/personas_hclust.R
  R/tm_freq.R
  R/totals_reorder.R
  R/workpatterns_area.R
  R/workpatterns_hclust.R
  R/workpatterns_rank.R
  _pkgdown.yml
  data/em_data.rda
  man/afterhours_dist.Rd
  man/create_line.Rd
  man/flag_ch_ratio.Rd
  man/flag_outlooktime.Rd
  man/hr_trend.Rd
  man/identify_churn.Rd
  man/identify_query.Rd
  man/identify_tenure.Rd
  man/is_date_format.Rd
  man/network_leiden.Rd
  man/network_louvain.Rd
  man/network_p2p.Rd
  man/personas_hclust.Rd
  man/tm_freq.Rd
  man/totals_reorder.Rd
  man/workpatterns_area.Rd
  man/workpatterns_hclust.Rd
  man/workpatterns_rank.Rd
Labels: documentation, refactor

#50 Feature: changes to time series plots to start axis from origin
  R/create_line.R
  R/identify_holidayweeks.R
  man/identify_holidayweeks.Rd
Labels: enhancement

#53 Documentation: add lifecycle badges
  .Rbuildignore
  DESCRIPTION
  R/heat_colours.R
  R/network_describe.R
  R/network_leiden.R
  R/network_louvain.R
  R/network_p2p.R
  R/personas_hclust.R
  R/workpatterns_hclust.R
  man/figures/lifecycle-archived.svg
  man/figures/lifecycle-defunct.svg
  man/figures/lifecycle-deprecated.svg
  man/figures/lifecycle-experimental.svg
  man/figures/lifecycle-maturing.svg
  man/figures/lifecycle-questioning.svg
  man/figures/lifecycle-stable.svg
  man/figures/lifecycle-superseded.svg
  man/heat_colours.Rd
  man/network_describe.Rd
  man/network_leiden.Rd
  man/network_louvain.Rd
  man/network_p2p.Rd
  man/personas_hclust.Rd
  man/workpatterns_hclust.Rd
  vignettes/Change-over-time.Rmd
Labels: documentation
